### ISSUE TITLE
Winmidi does not connect to named devices

### ISSUE THREAD

**Issue by AstralStorm** [FluidSynth/fluidsynth#650]
### FluidSynth version
FluidSynth runtime version 2.1.2
Copyright (C) 2000-2020 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

FluidSynth executable version 2.1.2
Sample type=float

64-bit build from Windows Azure CI.

### Describe the bug
Winmidi driver does not connect to the named device on Windows 10, never finding it.

### Expected behavior
Winmidi driver should find and connect the named device.

### Steps to reproduce
fluidsynth -m winmidi -o midi.winmidi.device=somename -v

### Additional context
Windows 10 2004 19624.1000

Note the extra newlines. Adding newline in the name itself does not work either.

```
fluidsynth: debug: Using 'winmidi' midi driver
fluidsynth: debug: Testing midi device: Hilo Virtual MIDI In

fluidsynth: debug: Testing midi device: USB MIDI Interface

fluidsynth: error: Device <USB MIDI Interface> does not exists
Failed to create the MIDI thread; no MIDI input
will be available. You can access the synthesizer
through the console.
```

**Comment by derselbst** [comment]
I can't reproduce this. Executing `fluidsynth.exe -v -m winmidi -o midi.winmidi.device="LK USB IN  1"` works fine:

```
fluidsynth: debug: Using 'winmidi' midi driver
fluidsynth: debug: Testing midi device: LK USB IN  1

fluidsynth: debug: Selected midi device number: 0
```

`_stricmp` seems to fail in your case. But without debugging I can't tell why.

That newline is coming from the log message:

https://github.com/FluidSynth/fluidsynth/blob/d63524683ff3bd9f46bd8be503372bd91535fcb2/src/drivers/fluid_winmidi.c#L252

**Comment by derselbst** [comment]
I've committed a potential fix, pls test: https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=1840&view=results

**Comment by AstralStorm** [comment]
While the newlines no longer appear, I still get:
```
fluidsynth: debug: Using 'winmidi' midi driver
fluidsynth: debug: Testing midi device: Hilo Virtual MIDI In
fluidsynth: debug: Testing midi device: USB MIDI Interface
fluidsynth: debug: Testing midi device: loopMIDI Port
fluidsynth: error: Device <USB MIDI Interface> does not exists
```

Something more is amiss.

**Comment by derselbst** [comment]
Ok thanks. I'll add quotes to the debug output.
