### ISSUE TITLE
 Couldn't find the FluidSynth library

### ISSUE THREAD

**Issue by gongel** [FluidSynth/fluidsynth#657]
I have installed pyFluidSynth using pip, but  if I import fluidsynth the i get the error ImportError: Couldn't find the FluidSynth library.

**Comment by gongel** [comment]
I have fixed it by [ https://github.com/FluidSynth/fluidsynth/wiki/Download]( https://github.com/FluidSynth/fluidsynth/wiki/Download)

**Comment by tiedaneri** [comment]
i've install the fluidsynth using choco, but this error still occur when running upiano.
